SELECT 
CASE 
    -- WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN "1Q"
    WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN "1Q"
    WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN "2Q"
    WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN "3Q"
    ELSE '4Q'
END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;

-- QUARTER 함수가 있었..음!! 충격.......
-- QUARTER(날짜형) -> 분기별 숫자로 나타내줌... CONCAT 써서 문자열로 만들어주면됨.